name: flutter_upchunk
description: A chunk uploader based on the JS library https://github.com/muxinc/upchunk done by MUX, Inc.
version: 1.5.0
homepage: https://github.com/gabrielginter/flutter-upchunk

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.2
  connectivity_plus: ^4.0.1
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
